# Generated by Django 4.0 on 2022-01-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0005_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='email',
            field=models.CharField(max_length=250),
        ),
    ]
